### ISSUE TITLE
UnicodeData.txt referenced, but not in repository

### ISSUE THREAD

**Issue by ajnelson** [dfirlabs/ext-specimens#1]
I noticed this repository being referenced in SleuthKit Issue 2487.

Scanning through `generate-specimens-unicode-linux.sh`, I noticed a file `UnicodeData.txt` consumed by the script, but not tracked in this repository.

If you don't want to include the entire `UnicodeData.txt` in this repository, might a file be included for the purpose of demonstrating expected syntax?  Perhaps including [unicode snowman](https://www.fileformat.info/info/unicode/char/2603/browsertest.htm) ('SNOWMAN', U+2603)?

☃

**Comment by joachimmetz** [comment]
> consumed by the script, but not tracked in this repository.

correct since that is Unicode version dependent and can be obtained from unicode.org

Expected syntax is that UnicodeData.txt exists in the directory where the script is run, as can be derived from https://github.com/dfirlabs/ext-specimens/blob/main/generate-specimens-unicode-linux.sh#L81

**Comment by joachimmetz** [comment]
Added more explicit text in warning https://github.com/dfirlabs/ext-specimens/blob/main/generate-specimens-unicode-linux.sh#L83

**Comment by ajnelson-nist** [comment]
Thanks!
